# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "CodeNStuff"
description: > # this means to ignore newlines until "email:"
   I like to do things and stuff

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Mari Batilando'
author: 'Mari Batilando'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://maribatilando.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/Cal_a_Mar1
    desc: Follow my tweets!
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github-alt
    url:	https://github.com/mbatilando
    desc:	Check out my side projects
    share_url:
    share_title:
    share_link:

  - icon: google-plus
    url:	https://plus.google.com/+MariBatilando/posts
    desc: Add me on google+
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url:	https://www.linkedin.com/in/maribatilando
    desc: Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:
